### ISSUE TITLE
lua 5.2 env compatability

### ISSUE THREAD

**Issue by acrisci** [kikito/lua_missions#12]
I'm running Arch and the <code>lua</code> in my path is 5.2.2. When I follow the instructions in the readme file to start the missions,

    $ lua missions.lua

I get the following message
<pre>
lua: ./lib/agent.lua:127: attempt to call global 'setfenv' (a nil value)
stack traceback:
	./lib/agent.lua:127: in function 'load_mission'
	./lib/agent.lua:212: in function 'run_missions'
	missions.lua:29: in main chunk
	[C]: in ?
</pre>

This works fine.

    $ lua5.1 missions.lua

**Comment by kikito** [comment]
Hi @acrisci , I just uploaded a set of changes which make lua_missions compatible with Lua 5.2, in case you want to test them. I am closing this issue now.
