### ISSUE TITLE
Metatables not explained

### ISSUE THREAD

**Issue by ProjectDent** [kikito/lua_missions#20]
I just finished the metatables file, purely from guesswork or cheating from the console.

Metatables are not at all well explained. I'll have to look up a guide elsewhere to have any idea as to what those things are, or their purpose.

**Comment by kikito** [comment]
Hi there,

You give me very little to work with. How would you improve the metatables mission?

**Comment by kikito** [comment]
I am closing this down due to lack of activity. Please feel free to reopen if you want to continue this discussion.
