### ISSUE TITLE
It doesn't work at all

### ISSUE THREAD

**Issue by manfredlotz** [kikito/lua_missions#32]
Trying to get it work in Ubuntu 22.04 and EndeavourOS (Arch Linux based) I run

$ lua missions.lua

and get

``` 
Assertion failed: Expected false to be true
The error happened here:
	asserts.lua:2: in function <asserts.lua:1>
lua5.1: ./lib/agent.lua:153: attempt to concatenate a nil value
stack traceback:
	./lib/agent.lua:153: in function 'mission_print_report'
	./lib/agent.lua:239: in function 'print_report'
	./lib/agent.lua:253: in function 'execute'
	missions.lua:31: in main chunk
	[C]: ?
```

The same happens with lua 5.2, 5.3 or 5.4

**Comment by mathiasdonoso** [comment]
those are the missions, if you go to **missions/asserts.lua** and change the **2nd line**:
```lua
assert_true(false)
```
to
```lua
assert_true(true)
```

you should see a different error and continue to the next mission

**Comment by manfredlotz** [comment]
Ah, ok. Now I understand. 😁

Thanks.

**Comment by codecop** [comment]
Hi this issue could be closed

**Comment by manfredlotz** [comment]
True. Let's close it. -:)
